production=false
main_node=true

storage_dir="~/.chatroom"
redirect_base_url="localhost:5173"
api_base_url="http://localhost:8080"

[Auth]
token_secret=""


[HTTP]
https_enabled=true
cert_file="./cert.crt"
key_file="./cert.key"
cors_regexs=[
    "http(|s)://localhost:(5173|8080)",
    "http(|s)://127.0.0.1:(5173|8080)",
]
openssl_command=""


[Database]
host="127.0.0.1"
port=5432
user="postgres"
password="postgres"
database="chatroom"
schema="public"
ssl_mode="disable"



[Database.PGVector]
# https://github.com/pgvector/pgvector
enabled=true


[GitLab]
auth_enabled=false
auth_app_id=""
auth_app_secret=""
instance_url="https://gitlab.com"


[Google]
auth_enabled=false
auth_app_id=""
auth_app_secret=""


[OpenAI]
api_key=""