production=false
main_node=true
timezone="UTC"

storage_dir="~/.chatroom"
redirect_base_url="localhost:5173"
api_base_url="https://localhost:6500"

[Auth]
token_secret=""
token_issuer="chatroom"
token_audience="chatroom"
token_expiry_seconds=43200 # 12 hours
cookie_maxage=43200 # 12 hours
cookie_secure=true
cookie_http_only=true

[Notes]
directory="~/.chatroom/notes"

[HTTP]
scheme="https"
host="127.0.0.1"
react_dev_server_host="http://localhost:5173"
port=6500
https_enabled=true
cert_file=""
key_file=""
cors_regexs=[
    "http(|s)://localhost:(5173|6500)",
    "http(|s)://127.0.0.1:(5173|6500)",
]
openssl_command=""


[Database]
host="127.0.0.1"
port=5432
username="postgres"
password="postgres"
database="chatroom"
schema="public"
ssl_mode=""



[Database.PGVector]
# https://github.com/pgvector/pgvector
enabled=true


[GitLab]
auth_enabled=false
auth_app_id=""
auth_app_secret=""
instance_url="https://gitlab.com"


[Google]
auth_enabled=false
auth_app_id=""
auth_app_secret=""


[OpenAI]
api_key=""