info:
  contact: {}
paths:
  /page/:path:
    get:
      consumes:
      - application/json
      description: returns the content of a page based on it's path
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: returns the content of a page
      tags:
      - basic
swagger: "2.0"
